# Generated by Django 2.2.6 on 2019-10-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
